# Generated by Django 3.1.5 on 2021-01-06 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("idemia_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enrollmentrecord",
            name="_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("IN PROGRESS", "In Progress"),
                    ("SUCCESSFUL", "Successful"),
                    ("FAILED", "Failed"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
