# Generated by Django 3.1.5 on 2021-01-08 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("idemia_api", "0003_auto_20210106_1659"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="enrollmentrecord",
            options={"ordering": ["creation_date"]},
        ),
    ]
