# Generated by Django 3.1.5 on 2021-01-11 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("idemia_api", "0004_auto_20210108_1603"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="enrollmentrecord", options={"ordering": ["-creation_date"]},
        ),
    ]
