# Generated by Django 3.1.6 on 2021-03-01 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EnrollmentRecord",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("record_csp_uuid", models.UUIDField()),
                ("record_idemia_ueid", models.CharField(max_length=10)),
                (
                    "record_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("IN PROGRESS", "In Progress"),
                            ("SUCCESSFUL", "Successful"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-creation_date"],
                "unique_together": {("record_csp_uuid", "record_idemia_ueid")},
            },
        ),
    ]
