# Generated by Django 3.1.6 on 2021-03-19 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="enrollmentrecord",
            old_name="record_csp_id",
            new_name="csp_id",
        ),
        migrations.RenameField(
            model_name="enrollmentrecord",
            old_name="record_csp_uuid",
            new_name="csp_uuid",
        ),
        migrations.RenameField(
            model_name="enrollmentrecord",
            old_name="record_idemia_ueid",
            new_name="idemia_ueid",
        ),
        migrations.RenameField(
            model_name="enrollmentrecord",
            old_name="record_status",
            new_name="status",
        ),
        migrations.AlterUniqueTogether(
            name="enrollmentrecord",
            unique_together={("csp_uuid", "csp_id")},
        ),
    ]
