# Generated by Django 3.1.6 on 2021-03-01 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="enrollmentrecord",
            unique_together=set(),
        ),
    ]
