# Generated by Django 3.1.6 on 2021-03-19 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_auto_20210319_1855"),
    ]

    operations = [
        migrations.RenameField(
            model_name="enrollmentrecord",
            old_name="csp_uuid",
            new_name="csp_user_uuid",
        ),
        migrations.AlterField(
            model_name="enrollmentrecord",
            name="csp_id",
            field=models.CharField(max_length=16),
        ),
        migrations.AlterUniqueTogether(
            name="enrollmentrecord",
            unique_together={("csp_user_uuid", "csp_id")},
        ),
    ]
