# Generated by Django 3.1.6 on 2021-03-01 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_auto_20210301_2230"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="enrollmentrecord",
            unique_together={("record_csp_uuid", "record_idemia_ueid")},
        ),
    ]
