# Generated by Django 3.1.6 on 2021-03-02 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_auto_20210301_2231"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollmentrecord",
            name="record_csp_id",
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
