# Generated by Django 3.1.6 on 2021-02-24 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_auto_20210111_1613"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="enrollmentrecord",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="enrollmentrecord",
            name="last_name",
        ),
    ]
