# Generated by Django 3.1.6 on 2021-03-02 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_auto_20210302_2135"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enrollmentrecord",
            name="record_csp_id",
            field=models.CharField(max_length=50),
        ),
    ]
